### ISSUE TITLE
f2c.py ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#11]

**Comment by cethenmc** [comment]
I gave a long note in the tempconversion.py Issue ticket that might give you enough information for this one already.  To recap, I recorded a 6 of 8 _for now_.  You can reply to this ticket when corrections are pushed to Git Hub.

For f2c.py:
- I am unsure why convert_temp is solo on line 22 like you have it.  When you reply to this ticket with the corrections, could you let me know why you had it there (I want to ensure there is no misunderstanding of a concept)?
- Instead of prints in convert_temp(fInput), only have a single return.  You will want to add a print in the main function, so the main function prints the Celsius value for 32F.

**Comment by rherring2-matc** [comment]
I have uploaded the updated scripts from our discussion in class.
