### ISSUE TITLE
tempconversion.py ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#12]

**Comment by cethenmc** [comment]
Hi, Robert.  In the future, you will submit all lab scripts together as one issue ticket.  The only exception was the midterm (and the boolean.py week).

You steered in a slightly different direction than what we were seeking.  I am recording a **6 of 8** in the grade book for now.  However, you can reply to these Issue tickets when you have re-pushed changes to GitHub to aim for full credit.

Regarding tempconversion.py:
Typically, a calling script (like tempconversion.py) will call a function and print from within itself (not just accepting the print from within the script it is calling).  The returns are often simple 32 returns 0, 212 returns 100, -40 returns -40.  This makes the function more reusable to other calling scripts that may utilize the result differently.

For example, I have a third script for converting Celsius to Kelvin (K degrees), but I accept Fahrenheit as the input.  This c2k.py script will call to f2c.convert_temp() function to switch the inputted Fahrenheit temperature to Celsius, then run its formula with the return Celsius values.  If I have all of that excess printing of "The Input Temp was this:  The Celsius is this:" I will have to somehow strip out the correct number if I want to reuse it for this new script.  Not very reusable, even though you have it formatted descriptively.

The return value from the f2c script is critical, and this is why there were these requirements in the fc script:

The function must:

- Accept an Argument for the temperature value
- **Return the result** to the calling program (the calling program is tempconversion.py)

I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, since you are modifying the other pieces, you may want to consider modifying your tempconversion.py script to run that way.

Thanks.

Chris

**Comment by rherring2-matc** [comment]
I have uploaded the updated scripts from our discussion in class.

**Comment by cethenmc** [comment]
Perfect!  Thanks for making the changes. 8 of 8 (as I mentioned in the ticket for the f2c.py file).
