### ISSUE TITLE
Midterm Activity 1 Flow Contrrol ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#8]

**Comment by cethenmc** [comment]
Nice work, Robert.  The Midterm Activity for this session asked you to place the Midterm-if.txt file into the midterm directory.  You did that and designated the absolute path instead of the relative path.  In the future, it would be fantastic if you would just list the relative path or in this case just the file name.  Really nice job.  Perfect 33/33.
